server:
  port: 8988
spring:
  application:
    name: netty-rpc-provider
willian:
  rpc:
    service:
      server-port: 8989
      registry-address: 192.168.31.136:2181,192.168.31.136:2182,192.168.31.136:2183
      registry-type: 0