server:
  port: 8987
spring:
  application:
    name: netty-rpc-consumer
willian:
  rpc:
    client:
      registry-address: 192.168.31.136:2181,192.168.31.136:2182,192.168.31.136:2183
      registry-type: 0